# Generated by Django 2.0.7 on 2018-08-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=0),
        ),
    ]
