# Generated by Django 2.0.7 on 2018-08-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelTest', '0002_person_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
